[colors.primary]
background = '#19120d'
foreground = '#f0dfd7'

[colors.selection]
text = '#f0dfd7'
background = '#6e380f'

[colors.cursor]
text = '#19120d'
cursor = '#ffb689'

[colors.normal]
black   = '#19120d'
red     = '#e24980'
green   = '#98d66e'
yellow  = '#dbac7b'
blue    = '#be6e3c'
magenta = '#bf9378'
cyan    = '#ffb689'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f91'
green   = '#aae086'
yellow  = '#e8c197'
blue    = '#ffc496'
magenta = '#b0644f'
cyan    = '#97724d'
white   = '#ffffff'
