[colors.primary]
background = '#1a110e'
foreground = '#f1dfd9'

[colors.selection]
text = '#f1dfd9'
background = '#72351e'

[colors.cursor]
text = '#1a110e'
cursor = '#ffb59b'

[colors.normal]
black   = '#1a110e'
red     = '#e14982'
green   = '#9ad66e'
yellow  = '#dbab7b'
blue    = '#c06c4e'
magenta = '#bf9283'
cyan    = '#ffb59b'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f93'
green   = '#ace086'
yellow  = '#e8bf97'
blue    = '#ffc2a6'
magenta = '#b95f56'
cyan    = '#9d6f54'
white   = '#ffffff'
